### ISSUE TITLE
Code review by Xueyao Liang

### ISSUE THREAD

**Issue by liangxy8** [vaibhavb1996/MiniProject1#1]
Hi Vaibhav,

It`s my pleasure to review your code. Each part of your code is clear and have a good structure, and accompanied with detailed comments. Also it`s great to make on-screen instructions to guide user. And you also did a great job about handling exceptions with giving some feedback when user meet some common problems. But I still have some suggestions for you:

1. It will be great, if you can let users to input the number of tweets they want to get by themselves.

2. you may need to consider more about error handle. What happens if there are no images in twitter? And if the twitter handle is invalid, what will user do? 

Sincerely

**Comment by vaibhavb1996** [comment]
I didn't want the users to input the number of tweets themselves because then probably the output of the program won't be to the satisfaction of user. they may give a large number (which exceeds the API's limit) or a very small one (which will reduce the effectiveness of the program).

No images is something I have taken care of, see line 71 of tweetscanner.py
As far as wrong twitter handle is concerned, it is also taken care of, see line 29 of tweetscanner.py
